// Global Constants
const BARRACK_WOOD_COST = 50;
const SPEARMAN_WOOD_COST = 5; // Cost to train a spearman
const SPEARMAN_TRAIN_TIME = 10000; // 10 seconds training time
const SPEARMAN_LIMIT = 3; // Max number of spearmen per side
const SPEARMAN_HEALTH = 15; // Health for spearmen
const SPEARMAN_DPS = 1; // Damage per second
const SPEARMAN_ATTACK_DELAY = 1000; // Milliseconds between attacks (1 attack per second)
const SPEARMAN_ATTACK_RANGE = 45; // Range within which spearman can attack
const SPEARMAN_DEFENSE_RADIUS = 150; // Radius around buildings for defense goal
const WORKER_HEALTH = 10;
const HOUSE_HEALTH = 50;
const BARRACK_HEALTH = 50;
const PLAYER_HEALTH_BAR_COLOR = 0x00ff00; // Green for player units/buildings
const AI_HEALTH_BAR_COLOR = 0xff0000; // Red for AI units/buildings
const BUILDING_HEALTH_BAR_WIDTH = 32; // Width for building health bars
const UNIT_HEALTH_BAR_WIDTH = 28; // Width for unit health bars
const SPEARMAN_HEALTH_BAR_WIDTH = 40; // Width for spearman health bar
const UNIT_COLLISION_RADIUS = 20; // Radius for checking unit overlap
const HEALTH_BAR_HEIGHT = 8; // Main health bar height
const TRAINING_TEXT_STYLE = { font: '14px Arial', fill: '#000000', backgroundColor: '#ffffff', padding: { x: 5, y: 2 }, borderRadius: 4 }; // Style for training text bubble
const GOAL_TEXT_STYLE = { font: '10px Arial', fill: '#ffffff', backgroundColor: 'rgba(0,0,0,0.6)', padding: { x: 3, y: 1 }, borderRadius: 3 };
const FOG_CELL_SIZE = 64; // Size of fog of war grid cells
const FOG_COLOR = 0x000000; // Black fog
const FOG_ALPHA = 0.75; // Semi-transparent fog
const DAMAGE_TEXT_STYLE = { font: 'bold 16px Arial', fill: '#ff0000', stroke: '#000000', strokeThickness: 3 }; // Style for damage text
const DAMAGE_TEXT_DURATION = 1200; // Milliseconds for damage text animation
const DAMAGE_TEXT_Y_RISE = -60; // Pixels damage text rises
const ATTACK_FLASH_DURATION = 350; // Milliseconds for attack flash (increased further)
const ATTACK_FLASH_WIDTH = 4; // Width of the flash beam
const ATTACK_FLASH_LENGTH_FACTOR = 0.75; // Flash length relative to distance
const MIN_ATTACK_FLASH_LENGTH = 10; // Minimum flash length
const DAMAGE_FLASH_TINT = 0xff0000; // Red tint for damage flash
const DAMAGE_FLASH_DURATION = 150; // Milliseconds for damage flash